/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas.pkg5.pkg1;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author KANG KODING
 */
public class FormNilai extends javax.swing.JInternalFrame {
    Connection con;
    ResultSet rs;
    PreparedStatement pst;
    DefaultTableModel tm;
    /**
     * Creates new form FormNilai
     */
    public FormNilai() {
        initComponents();
        connect();
        refresh();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelNilai = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        inputNilaiUTS = new javax.swing.JTextField();
        tbl_hapus = new javax.swing.JButton();
        tbl_update = new javax.swing.JButton();
        tbl_tambah = new javax.swing.JButton();
        inputNilaiAkhir = new javax.swing.JTextField();
        inputNilaiHarian = new javax.swing.JTextField();
        inputNilaiUAS = new javax.swing.JTextField();
        tbl_hitung = new javax.swing.JButton();
        nis = new javax.swing.JTextField();
        idNilai = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        tabelNilai.setAutoCreateRowSorter(true);
        tabelNilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelNilai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelNilaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelNilai);

        jLabel1.setFont(new java.awt.Font("EXCELSIOR SANS", 0, 24)); // NOI18N
        jLabel1.setText("Form Nilai");

        jLabel2.setText("Nilai Harian");

        jLabel3.setText("Nilai UAS");

        jLabel4.setText("Nilai UTS");

        jLabel6.setText("Nilai Akhir");

        inputNilaiUTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNilaiUTSActionPerformed(evt);
            }
        });

        tbl_hapus.setText("Delete");
        tbl_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl_hapusActionPerformed(evt);
            }
        });

        tbl_update.setText("Update");
        tbl_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl_updateActionPerformed(evt);
            }
        });

        tbl_tambah.setText("Add");
        tbl_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl_tambahActionPerformed(evt);
            }
        });

        inputNilaiUAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNilaiUASActionPerformed(evt);
            }
        });

        tbl_hitung.setText("Hitung");
        tbl_hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl_hitungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(26, 26, 26)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(27, 27, 27)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(inputNilaiHarian, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                    .addComponent(inputNilaiUTS)
                                    .addComponent(inputNilaiUAS))
                                .addGap(18, 18, 18)
                                .addComponent(tbl_hitung))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tbl_tambah)
                                .addGap(18, 18, 18)
                                .addComponent(tbl_update)
                                .addGap(18, 18, 18)
                                .addComponent(tbl_hapus))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nis)
                                    .addComponent(idNilai, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(inputNilaiAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(inputNilaiHarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputNilaiUTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputNilaiUAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbl_hitung))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbl_tambah)
                            .addComponent(tbl_update)
                            .addComponent(tbl_hapus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(inputNilaiAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(idNilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl_updateActionPerformed
        try {
           con.createStatement().executeUpdate("UPDATE nilaiakhir SET nilaiharian='"+inputNilaiHarian.getText()+"', nilaiuts='"+inputNilaiUTS.getText()+"', nilaiuas='"+inputNilaiUAS.getText()+"', nilaiakhir='"+inputNilaiAkhir.getText()+"' WHERE id='"+idNilai.getText()+"'");
            
            refresh();
            idNilai.setText("");
            nis.setText("");
            inputNilaiAkhir.setText("");
            inputNilaiHarian.setText("");
            inputNilaiUTS.setText("");
            inputNilaiUAS.setText("");
        } catch(Exception e) {
            System.out.print("ERROR KUERI KE DATABASE:\n" + e + "\n\n");
        }
    }//GEN-LAST:event_tbl_updateActionPerformed

    private void inputNilaiUTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNilaiUTSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNilaiUTSActionPerformed

    private void tbl_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl_tambahActionPerformed
        try {
              PreparedStatement ps = con.prepareStatement("INSERT INTO nilaiakhir VALUES (?,?,?,?,?,?)");
              ps.setString(1, idNilai.getText());
              ps.setString(2, nis.getText());
              ps.setString(3, inputNilaiHarian.getText());
              ps.setString(4, inputNilaiUTS.getText());
              ps.setString(5, inputNilaiUAS.getText()); 
              ps.setString(6, inputNilaiAkhir.getText());
              ps.executeUpdate();
            
            refresh();
            idNilai.setText("");
            nis.setText("");
            inputNilaiAkhir.setText("");
            inputNilaiHarian.setText("");
            inputNilaiUTS.setText("");
            inputNilaiUAS.setText("");
        } catch(Exception e) {
            System.out.print("ERROR KUERI KE DATABASE:\n" + e + "\n\n");
        }
    }//GEN-LAST:event_tbl_tambahActionPerformed

    private void tbl_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl_hapusActionPerformed
       int k = JOptionPane.showConfirmDialog(null, "Yakin Mau di hapus? ", "Warning", JOptionPane.YES_NO_OPTION);
       if(k == JOptionPane.YES_OPTION){
       try {
            PreparedStatement ps = con.prepareStatement("DELETE FROM nilaiakhir WHERE id=?");
            ps.setString(1, idNilai.getText());
            ps.executeUpdate();
            
            refresh();
            idNilai.setText("");
            nis.setText("");
            inputNilaiAkhir.setText("");
            inputNilaiHarian.setText("");
            inputNilaiUTS.setText("");
            inputNilaiUAS.setText("");
        } catch(Exception e) {
            System.out.print("ERROR KUERI KE DATABASE:\n" + e + "\n\n");
        }
       }
    }//GEN-LAST:event_tbl_hapusActionPerformed

    private void tabelNilaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelNilaiMouseClicked
        idNilai.setText(tm.getValueAt(tabelNilai.getSelectedRow(),0).toString());
        nis.setText(tm.getValueAt(tabelNilai.getSelectedRow(),1).toString());
        inputNilaiHarian.setText(tm.getValueAt(tabelNilai.getSelectedRow(),2).toString());
        inputNilaiUTS.setText(tm.getValueAt(tabelNilai.getSelectedRow(),3).toString());
        inputNilaiUAS.setText(tm.getValueAt(tabelNilai.getSelectedRow(),4).toString());
        inputNilaiAkhir.setText(tm.getValueAt(tabelNilai.getSelectedRow(),5).toString());
    }//GEN-LAST:event_tabelNilaiMouseClicked

    private void inputNilaiUASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNilaiUASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNilaiUASActionPerformed

    private void tbl_hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl_hitungActionPerformed
        Double nilaiHarian,nilaiUAS,nilaiUTS,nilaiAkhir;
        nilaiHarian = Double.parseDouble(inputNilaiHarian.getText());
        nilaiUTS = Double.parseDouble(inputNilaiUTS.getText());
        nilaiUAS = Double.parseDouble(inputNilaiUAS.getText());
        nilaiAkhir = (nilaiHarian+nilaiUTS+nilaiUAS)/3;
        String nilai = nilaiAkhir.toString();
        inputNilaiAkhir.setText(nilai);
        
    }//GEN-LAST:event_tbl_hitungActionPerformed

    private void connect() {
        
        con = null;
       try{
           Class.forName("com.mysql.jdbc.Driver");
           con = DriverManager.getConnection("jdbc:mysql://localhost/db_sekolah", "root","");
           
       }catch(Exception e){
           System.out.println("Gagal Mengkoneksikan Ke database");
       }
    }

    
    private void refresh() {
        tm = new DefaultTableModel(null, new Object[] { "ID","NIS", "Nilai Harian", "Nilai UTS", "Nilai UAS", "Nilai Akhir" });
        tabelNilai.setModel(tm);
        tm.getDataVector().removeAllElements();
 
       
        try {
            PreparedStatement s = con.prepareStatement("SELECT * FROM nilaiakhir");
            ResultSet r = s.executeQuery();
            while(r.next()) {
                Object[] data = {
                    r.getString(1),
                    r.getString(2),
                    r.getString(3),
                    r.getString(4),
                    r.getString(5),
                    r.getString(6)
                   
                };
                tm.addRow(data);
            }
        } catch(Exception e) {
            System.out.print("ERROR KUERI KE DATABASE:\n" + e + "\n\n");
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idNilai;
    private javax.swing.JTextField inputNilaiAkhir;
    private javax.swing.JTextField inputNilaiHarian;
    private javax.swing.JTextField inputNilaiUAS;
    private javax.swing.JTextField inputNilaiUTS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nis;
    private javax.swing.JTable tabelNilai;
    private javax.swing.JButton tbl_hapus;
    private javax.swing.JButton tbl_hitung;
    private javax.swing.JButton tbl_tambah;
    private javax.swing.JButton tbl_update;
    // End of variables declaration//GEN-END:variables
}
